apiVersion: v1
kind: pod
metadata:
  name: postgres-app-pods
  labels:
    app: demo-voting-app
    name: postgres-pod
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        -containerPort: 5432