apiVersion: v1
kind: pod
metadata:
  name: redis
  labels:
    app: demo-voting-app
    name: redis-pod
spec:
  containers:
    - name: redis
      image: redis
      ports:
        -containerPort: 6379